export enum Roles {
    ADMIN_APP = "ADMIN_APP",
    COORDONNATEUR = "COORDONNATEUR",
    PROFESSEUR = "PROFESSEUR",
    ETUDIANT = "ETUDIANT",
    ADMIN_ABSENCE = "ADMIN_ABSENCE",
    SECRETAIRE_GENERAL = "SECRETAIRE_GENERAL",
    CHEF_SCOLARITE = "CHEF_SCOLARITE",
  }
  